#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Build ONLY the artifacts the paper actually includes, into paper_figs/.
#
#   bash code/make_paper_figs.sh
#
# figures/figs_sept/ stays the working directory where scripts write everything
# they produce, including variants and sensitivities. paper_figs/ is the curated
# set: if it is not here, it is not in the paper. That makes the eventual cleanup
# of the codebase a matter of tracing back from this list.
#
# Add an artifact by adding a line to ARTIFACTS below (artifact:script).
# ---------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")/.."
PY="./venv/bin/python"
export MPLBACKEND=Agg
DEST="paper_figs"
SRC="figures/figs_sept"

# artifact : producing script
ARTIFACTS=(
  "fig1_grid:figure1_grid_ft.py"                        # Fig 1, main text
  "fig4_forecast_2panel:figure_forecast_ft.py"          # Fig 4, main text
  "fig2_hard_distributions_success:figure2_ft.py"       # Fig 2, main text
  "fig1_grid_alltraces:figure1_grid_ft.py"              # appendix: all attempts
)
TABLES=(
  "table_decay:table_decay.py"                          # main regression table
  "table_floor_robustness:table_floor_robustness.py"    # appendix robustness
)

mkdir -p "$DEST"

# run each producing script once, in a stable order
# dedup while preserving order (macOS ships bash 3.2, so no mapfile)
UNIQ=""
for a in "${ARTIFACTS[@]}"; do
  s="${a#*:}"
  case " $UNIQ " in *" $s "*) ;; *) UNIQ="$UNIQ $s" ;; esac
done
for s in $UNIQ; do
  printf '\n\033[1m=== %s ===\033[0m\n' "$s"
  "$PY" "code/$s" 2>&1 | grep -vE "UserWarning|warnings.warn|tight_layout" || true
  [ "${PIPESTATUS[0]}" -eq 0 ] || { echo "FAILED: $s"; exit 1; }
done

for t in "${TABLES[@]}"; do
  name="${t%%:*}"; script="${t#*:}"
  printf '\n\033[1m=== %s ===\033[0m\n' "$script"
  "$PY" "code/$script" "$DEST/$name.tex" 2>&1 | grep -vE "UserWarning|warnings.warn" || true
  [ "${PIPESTATUS[0]}" -eq 0 ] || { echo "FAILED: $script"; exit 1; }
done

echo
for a in "${ARTIFACTS[@]}"; do
  name="${a%%:*}"
  for ext in pdf png; do
    [ -f "$SRC/$name.$ext" ] || { echo "MISSING: $SRC/$name.$ext"; exit 1; }
    cp "$SRC/$name.$ext" "$DEST/$name.$ext"
  done
  echo "  -> $DEST/$name.{pdf,png}"
done

# provenance, so a future reader knows what produced what
{
  echo "# paper_figs — the curated set"
  echo
  echo "Generated by \`bash code/make_paper_figs.sh\` on $(date -u +%Y-%m-%d)."
  echo "Commit: $(git rev-parse --short HEAD)"
  echo
  echo "If an artifact is not listed here, it is not in the paper. Everything else"
  echo "a script produces stays in \`figures/figs_sept/\`."
  echo
  echo "| Artifact | Produced by | Where |"
  echo "| --- | --- | --- |"
  for a in "${ARTIFACTS[@]}"; do
    echo "| \`${a%%:*}.pdf\` | \`code/${a#*:}\` | see below |"
  done
  for t in "${TABLES[@]}"; do
    echo "| \`${t%%:*}.tex\` | \`code/${t#*:}\` | see below |"
  done
  echo
  echo "## Sample"
  echo
  echo "All artifacts use the **40 competition problems** (AIME 2026 I/II + HMMT"
  echo "February 2026); MATH-500 is excluded and the floor is **316 tokens**."
  echo "Validity is \`tok >= 50\`; a zero-length thinking block does not invalidate a"
  echo "trace. See the run-hygiene section of the top-level README."
} > "$DEST/MANIFEST.md"

echo
echo "Wrote $DEST/ ($(ls "$DEST" | wc -l | tr -d ' ') files) + MANIFEST.md"
