"""Emit the appendix block showing the judge prompts verbatim.

Reads the live *_v0.txt templates so the appendix cannot drift from what was
actually sent, and marks the one line we changed from upstream.

    python code/llm_judge/make_prompt_appendix.py paper_figs/appendix_judge_prompts.tex
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UPSTREAM_LINE = "You will be provided with text from the internet."
OUR_LINE = ("You will be provided with the reasoning trace of a language model "
            "solving a competition mathematics problem.")


def esc(s):
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


def block(behaviour):
    txt = open(os.path.join(HERE, f"{behaviour}_v0.txt")).read().rstrip()
    out = [r"\paragraph{%s.}" % behaviour.capitalize(), r"\begin{quote}\small\itshape"]
    for line in txt.splitlines():
        if not line.strip():
            out.append(r"\medskip"); continue
        if line.strip() == OUR_LINE:                      # flag our single edit
            out.append(r"\textbf{[edited]} " + esc(line) + r"\\")
        else:
            out.append(esc(line) + r"\\")
    out.append(r"\end{quote}")
    return "\n".join(out)


def main(path=None):
    parts = [
        r"% Appendix: judge prompts. Generated by code/llm_judge/make_prompt_appendix.py",
        r"\subsection*{Behaviour-judging prompts}",
        r"""Counts of backtracking and verification come from an LLM judge
(\texttt{gemini-2.5-flash}, temperature 0) given one whole reasoning trace and one
prompt per behaviour. The prompts are reproduced verbatim from
\citet{gandhi2025cognitive}'s \texttt{pretraining\_analysis/prompts/}, with a
single edit: their opening line, ``You will be provided with text from the
internet.'', is replaced by the line marked \textbf{[edited]} below, because we
apply them to reasoning traces rather than web text. Nothing else is changed, and
there is no system message --- their pipeline sends the formatted template as the
only user message. The trace is substituted for \texttt{\{response\}}.""",
        block("backtracking"),
        block("verification"),
    ]
    tex = "\n\n".join(parts) + "\n"
    if path:
        open(path, "w").write(tex)
        print(f"wrote {path}")
    else:
        print(tex)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
